---

- name: Create npm global directory
  file:
    path: "{{ npm_config_prefix }}"
    owner: "{{ nodejs_install_npm_user }}"
    group: "{{ nodejs_install_npm_user }}"
    state: directory


- name: Add npm_config_prefix bin directory to global $PATH.
  template:
    src: npm.sh.j2
    dest: /etc/profile.d/npm.sh
    mode: 0644

- set_fact: npm_all_env="{{ proxy_env|combine(npm_env) }}"

# - debug: msg="{{ item.key }} = {{ item.value }}"
#   with_dict: "{{ npm_all_env }}"

# TODO: Remove this task after Ansible 2.x npm module bug is fixed. See:
# https://github.com/ansible/ansible-modules-extras/issues/1375
- name: Ensure npm global packages are installed.
  npm:
    name: "{{ item.name }}"
    version: "{{ item.version | default('latest') }}"
    global: yes
    state: present
  environment:
    "{{ npm_all_env }}"
  with_items: "{{ nodejs_npm_global_packages }}"


- name: Ensure npm global packages are at the latest release.
  npm:
    name: "{{ item.name }}"
    version: "{{ item.version | default('latest') }}"
    global: yes
    state: latest
  environment:
    "{{ npm_all_env }}"
  with_items: "{{ nodejs_npm_global_packages }}"
