---

#########################
# Common deps           #
#########################
- hosts: all
  gather_facts: True
  become: true
  become_method: 'sudo'
  tags: common
  roles:
    - ansible-common-dependencies


#########################
# LVM partioning        #
#########################
- hosts: all
  gather_facts: True
  become: true
  become_method: 'sudo'
  tags: filesystem
  roles:
    - filesystem


#########################
# Java                  #
#########################
- hosts: all
  gather_facts: True
  become: true
  become_method: 'sudo'
  tags: java
  roles:
    - ansible-java



#########################
# Maven                 #
#########################

- hosts: all
  gather_facts: True
  become: true
  become_method: 'sudo'
  tags: maven
  roles:
    - maven
