---

- name: Add Logstash Repo Key
  apt_key: >
    url="{{ logstash_repo_key }}"
    state=present
    validate_certs={{ validate_apt_certificates }}
  environment: "{{ proxy_env }}"


- name: Add Logstash Debian repository
  shell: echo "{{ logstash_apt_repo }}" | sudo tee "{{ logstash_apt_source_list }}"


- name: Install Logstash
  apt: >
    pkg=logstash
    update_cache=yes
    state="{{ elk_version }}"
  environment: "{{ proxy_env }}"


# add version lock
- name: Include version lock for ELK Stack
  include: version-lock.yml
  when: elk_version_lock


# needed for init.d
- name: generate sysv script manually
  command: bash /usr/share/logstash/bin/system-install /etc/logstash/startup.options sysv


- name: Configuring Logstash Node
  template: >
    src="logstash.yml.j2"
    dest="{{ logstash_config_dir }}/logstash.yml"
    owner="{{ logstash_user }}"
    group="{{ logstash_group }}"
    mode=0664
    force=yes
  when: logstash_config_dir is defined


# init only
- name: Configure default settings for Logstash
  template: >
    src="logstash.default.j2"
    dest="/etc/default/logstash"
    owner=root
    group=root
    mode=0644
    backup=no
  when: logstash_defaults is defined
  notify: Restart Logstash


- name: Copy jvm.options File for Instance
  template: >
    src="jvm.options.j2"
    dest="{{ logstash_config_dir }}/jvm.options"
    owner="{{ logstash_user }}"
    group="{{ logstash_group }}"
    mode=0664
    force=yes
  when: logstash_config_dir is defined
  notify: Restart Logstash


# Fix permissions
- name: Configuring Log directory
  file: >
    path="{{ logstash_path_logs }}"
    state=directory
    owner="{{ logstash_user }}"
    group="{{ logstash_group }}"
    recurse=yes
  when: logstash_path_logs is defined


- name: Configuring Data directory
  file: >
    path="{{ logstash_path_data }}"
    state=directory
    owner="{{ logstash_user }}"
    group="{{ logstash_group }}"
    recurse=yes
  when: logstash_path_data is defined


# # Configure index templates directory
# - name: Configuring directories
#   file: >
#     path="{{ logstash_index_templates_dir }}"
#     state=directory
#     owner=root
#     group=root
#     recurse=yes
#   when: logstash_index_templates_dir is defined


# Register Logstash service to start on boot
- name: Ensure Logstash is started on boot
  service: >
    name=logstash
    enabled={{ logstash_service_startonboot }}
    state={{ logstash_service_state }}
