---

- name: Load Licence from file
  local_action: >
    set_fact es_xpack_licence="{{ lookup('file', 'xpack-licence.json') }}"

- name: Activate ES license (without security authentication)
  uri:
    method: PUT
    url: "http://{{ elasticsearch_api_host }}:{{ elasticsearch_api_port }}/_license?acknowledge=true"
    body_format: json
    body: "{{ es_xpack_licence }}"
    return_content: yes
  register: license_activated
  no_log: True
  when: (xpack_security_enabled == "false") and (es_xpack_licence is defined)
  failed_when: >
    license_activated.status != 200 or
    license_activated.json.license_status is not defined or
    license_activated.json.license_status != 'valid'

# - name: Activate ES license (with security authentication)
#   uri:
#     method: PUT
#     url: "http://{{es_api_host}}:{{es_api_port}}/_license?acknowledge=true"
#     user: "{{es_api_basic_auth_username}}"
#     password: "{{es_api_basic_auth_password}}"
#     body_format: json
#     force_basic_auth: yes
#     body: "{{ es_xpack_license }}"
#     return_content: yes
#   register: license_activated
#   no_log: True
#   when: xpack_security_enabled == "true"
#   failed_when: >
#     license_activated.status != 200 or
#     license_activated.json.license_status is not defined or
#     license_activated.json.license_status != 'valid'


- debug:
    msg: "License: {{ license_activated.content }}"
