---

# Configure Elasticsearch Node
- name: Configuring Elasticsearch Node
  template: >
    src="elasticsearch.yml.j2"
    dest="{{ elasticsearch_conf_dir }}/elasticsearch.yml"
    owner=root
    group="{{ elasticsearch_group }}"
    mode=0750
  when: elasticsearch_conf_dir is defined


# for init only
- name: Configure Elasticsearch Service Defaults (init.d)
  template: >
    src="elasticsearch.default.j2"
    dest=/etc/default/elasticsearch
    owner=root
    group=root
    mode=0644
  notify: Restart Elasticsearch


- name: Copy jvm.options File for Instance
  template: >
    src="jvm.options.j2"
    dest="{{ elasticsearch_conf_dir }}/jvm.options"
    owner=root
    group="{{ elasticsearch_group }}"
    mode=0664
    force=yes
  when: elasticsearch_conf_dir is defined
  notify: Restart Elasticsearch
