---

# Configure user and group
- name: Configuring user and group
  group: name={{ elasticsearch_group }}

- user: >
      name={{ elasticsearch_user }}
      group={{ elasticsearch_group }}
      createhome=no


# Add repo and install Elasticsearch
- name: Add Elasticsearch APT Key
  apt_key: >
      url="{{ elasticsearch_repo_key }}"
      state=present
      validate_certs={{ validate_apt_certificates }}
  environment:
    "{{ proxy_env }}"


- name: Add Elasticsearch Debian repository
  shell: echo "{{ elasticsearch_debian_repo }}" | sudo tee "{{ elasticsearch_apt_source_list }}"


- name: Install Elasticsearch
  apt: >
      name=elasticsearch
      update_cache=yes
      state="{{ elk_version }}"
  environment:
    "{{ proxy_env }}"


# add version lock
- name: Include version lock for ELK Stack
  include: version-lock.yml
  when: elk_version_lock


# Fix permissions
- name: Fix directory permissions
  file: >
    path="{{ elasticsearch_home_dir }}"
    state=directory
    owner=root
    group="{{ elasticsearch_group }}"
    recurse=yes


# Add directories for templates and scripts
- name: Add templates dir
  file: >
      path="{{ elasticsearch_templates_dir }}"
      state=directory
      owner="{{ elasticsearch_user }}"
      group="{{ elasticsearch_group }}"
      recurse=yes
  when: (elasticsearch_templates_dir is defined)


- name: Add scripts dir
  file: >
      path="{{ elasticsearch_scripts_dir }}"
      state=directory
      owner="{{ elasticsearch_user }}"
      group="{{ elasticsearch_group }}"
      recurse=yes
  when: (elasticsearch_scripts_dir is defined)
